/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as TermsRouteImport } from './../routes/terms'
import { Route as SupportRouteImport } from './../routes/support'
import { Route as PrivacyRouteImport } from './../routes/privacy'
import { Route as PricingRouteImport } from './../routes/pricing'
import { Route as PassengerSignupRouteImport } from './../routes/passenger-signup'
import { Route as DriverSignupRouteImport } from './../routes/driver-signup'
import { Route as ContactRouteImport } from './../routes/contact'
import { Route as AboutRouteImport } from './../routes/about'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as PassengerIndexRouteImport } from './../routes/passenger.index'
import { Route as DriverIndexRouteImport } from './../routes/driver.index'
import { Route as PassengerSettingsRouteImport } from './../routes/passenger.settings'
import { Route as PassengerSavedRouteImport } from './../routes/passenger.saved'
import { Route as PassengerHistoryRouteImport } from './../routes/passenger.history'
import { Route as DriverSettingsRouteImport } from './../routes/driver.settings'
import { Route as DriverPendingRouteImport } from './../routes/driver.pending'
import { Route as DriverHistoryRouteImport } from './../routes/driver.history'
import { Route as DriverEarningsRouteImport } from './../routes/driver.earnings'
import { Route as AuthRiderSignupRouteImport } from './../routes/auth.rider-signup'
import { Route as AuthPassengerSignupRouteImport } from './../routes/auth.passenger-signup'
import { Route as AuthLoginRouteImport } from './../routes/auth.login'
import { Route as AdminPricingRouteImport } from './../routes/admin.pricing'
import { Route as PassengerRideRideIdRouteImport } from './../routes/passenger.ride.$rideId'
import { Route as DriverRideRideIdRouteImport } from './../routes/driver.ride.$rideId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerSignupRoute = PassengerSignupRouteImport.update({
  id: '/passenger-signup',
  path: '/passenger-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/driver-signup',
  path: '/driver-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/passenger/',
  path: '/passenger/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerSettingsRoute = PassengerSettingsRouteImport.update({
  id: '/passenger/settings',
  path: '/passenger/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerSavedRoute = PassengerSavedRouteImport.update({
  id: '/passenger/saved',
  path: '/passenger/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerHistoryRoute = PassengerHistoryRouteImport.update({
  id: '/passenger/history',
  path: '/passenger/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSettingsRoute = DriverSettingsRouteImport.update({
  id: '/driver/settings',
  path: '/driver/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverPendingRoute = DriverPendingRouteImport.update({
  id: '/driver/pending',
  path: '/driver/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/driver/history',
  path: '/driver/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/driver/earnings',
  path: '/driver/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRiderSignupRoute = AuthRiderSignupRouteImport.update({
  id: '/auth/rider-signup',
  path: '/auth/rider-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPassengerSignupRoute = AuthPassengerSignupRouteImport.update({
  id: '/auth/passenger-signup',
  path: '/auth/passenger-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRideRideIdRoute = PassengerRideRideIdRouteImport.update({
  id: '/passenger/ride/$rideId',
  path: '/passenger/ride/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRideRideIdRoute = DriverRideRideIdRouteImport.update({
  id: '/driver/ride/$rideId',
  path: '/driver/ride/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/driver-signup': typeof DriverSignupRoute
  '/passenger-signup': typeof PassengerSignupRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passenger-signup': typeof AuthPassengerSignupRoute
  '/auth/rider-signup': typeof AuthRiderSignupRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/pending': typeof DriverPendingRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/saved': typeof PassengerSavedRoute
  '/passenger/settings': typeof PassengerSettingsRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/driver/ride/$rideId': typeof DriverRideRideIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/driver-signup': typeof DriverSignupRoute
  '/passenger-signup': typeof PassengerSignupRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passenger-signup': typeof AuthPassengerSignupRoute
  '/auth/rider-signup': typeof AuthRiderSignupRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/pending': typeof DriverPendingRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/saved': typeof PassengerSavedRoute
  '/passenger/settings': typeof PassengerSettingsRoute
  '/driver': typeof DriverIndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/driver/ride/$rideId': typeof DriverRideRideIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/driver-signup': typeof DriverSignupRoute
  '/passenger-signup': typeof PassengerSignupRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/passenger-signup': typeof AuthPassengerSignupRoute
  '/auth/rider-signup': typeof AuthRiderSignupRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/pending': typeof DriverPendingRoute
  '/driver/settings': typeof DriverSettingsRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/saved': typeof PassengerSavedRoute
  '/passenger/settings': typeof PassengerSettingsRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/driver/ride/$rideId': typeof DriverRideRideIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/driver-signup'
    | '/passenger-signup'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/admin/pricing'
    | '/auth/login'
    | '/auth/passenger-signup'
    | '/auth/rider-signup'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/pending'
    | '/driver/settings'
    | '/passenger/history'
    | '/passenger/saved'
    | '/passenger/settings'
    | '/driver/'
    | '/passenger/'
    | '/driver/ride/$rideId'
    | '/passenger/ride/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/driver-signup'
    | '/passenger-signup'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/admin/pricing'
    | '/auth/login'
    | '/auth/passenger-signup'
    | '/auth/rider-signup'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/pending'
    | '/driver/settings'
    | '/passenger/history'
    | '/passenger/saved'
    | '/passenger/settings'
    | '/driver'
    | '/passenger'
    | '/driver/ride/$rideId'
    | '/passenger/ride/$rideId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/driver-signup'
    | '/passenger-signup'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/admin/pricing'
    | '/auth/login'
    | '/auth/passenger-signup'
    | '/auth/rider-signup'
    | '/driver/earnings'
    | '/driver/history'
    | '/driver/pending'
    | '/driver/settings'
    | '/passenger/history'
    | '/passenger/saved'
    | '/passenger/settings'
    | '/driver/'
    | '/passenger/'
    | '/driver/ride/$rideId'
    | '/passenger/ride/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DriverSignupRoute: typeof DriverSignupRoute
  PassengerSignupRoute: typeof PassengerSignupRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthPassengerSignupRoute: typeof AuthPassengerSignupRoute
  AuthRiderSignupRoute: typeof AuthRiderSignupRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverPendingRoute: typeof DriverPendingRoute
  DriverSettingsRoute: typeof DriverSettingsRoute
  PassengerHistoryRoute: typeof PassengerHistoryRoute
  PassengerSavedRoute: typeof PassengerSavedRoute
  PassengerSettingsRoute: typeof PassengerSettingsRoute
  DriverIndexRoute: typeof DriverIndexRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
  DriverRideRideIdRoute: typeof DriverRideRideIdRoute
  PassengerRideRideIdRoute: typeof PassengerRideRideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger-signup': {
      id: '/passenger-signup'
      path: '/passenger-signup'
      fullPath: '/passenger-signup'
      preLoaderRoute: typeof PassengerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-signup': {
      id: '/driver-signup'
      path: '/driver-signup'
      fullPath: '/driver-signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/passenger'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/settings': {
      id: '/passenger/settings'
      path: '/passenger/settings'
      fullPath: '/passenger/settings'
      preLoaderRoute: typeof PassengerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/saved': {
      id: '/passenger/saved'
      path: '/passenger/saved'
      fullPath: '/passenger/saved'
      preLoaderRoute: typeof PassengerSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/history': {
      id: '/passenger/history'
      path: '/passenger/history'
      fullPath: '/passenger/history'
      preLoaderRoute: typeof PassengerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/settings': {
      id: '/driver/settings'
      path: '/driver/settings'
      fullPath: '/driver/settings'
      preLoaderRoute: typeof DriverSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/pending': {
      id: '/driver/pending'
      path: '/driver/pending'
      fullPath: '/driver/pending'
      preLoaderRoute: typeof DriverPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/driver/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/driver/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/rider-signup': {
      id: '/auth/rider-signup'
      path: '/auth/rider-signup'
      fullPath: '/auth/rider-signup'
      preLoaderRoute: typeof AuthRiderSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passenger-signup': {
      id: '/auth/passenger-signup'
      path: '/auth/passenger-signup'
      fullPath: '/auth/passenger-signup'
      preLoaderRoute: typeof AuthPassengerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/ride/$rideId': {
      id: '/passenger/ride/$rideId'
      path: '/passenger/ride/$rideId'
      fullPath: '/passenger/ride/$rideId'
      preLoaderRoute: typeof PassengerRideRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/ride/$rideId': {
      id: '/driver/ride/$rideId'
      path: '/driver/ride/$rideId'
      fullPath: '/driver/ride/$rideId'
      preLoaderRoute: typeof DriverRideRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DriverSignupRoute: DriverSignupRoute,
  PassengerSignupRoute: PassengerSignupRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthPassengerSignupRoute: AuthPassengerSignupRoute,
  AuthRiderSignupRoute: AuthRiderSignupRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverPendingRoute: DriverPendingRoute,
  DriverSettingsRoute: DriverSettingsRoute,
  PassengerHistoryRoute: PassengerHistoryRoute,
  PassengerSavedRoute: PassengerSavedRoute,
  PassengerSettingsRoute: PassengerSettingsRoute,
  DriverIndexRoute: DriverIndexRoute,
  PassengerIndexRoute: PassengerIndexRoute,
  DriverRideRideIdRoute: DriverRideRideIdRoute,
  PassengerRideRideIdRoute: PassengerRideRideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
